version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: on-failure
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=a-board
      - POSTGRES_USER=a-board
      - POSTGRES_PASSWORD=a-board
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
